name: Build/Test Windows

on:
  push:
    branches:
      - run-actions
      - devel
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-rfc:
    runs-on: windows-2025
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download gengetopt
        uses: robinraju/release-downloader@v1.12
        with:
          repository: rfmineguy/gengetopt-windows
          tag: gengetopt-2.23
          fileName: gengetopt-windows.zip

      - name: Extract gengetopt
        run: |
          tar -xf gengetopt-windows.zip -C gengetopt-install
        shell: bash

      - name: Add gengetopt to path
        run: |
          echo "${{github.workspace}}\gengetopt-install" >> $GITHUB_PATH
        shell: bash

      - name: Test gengetopt
        run: gengetopt.exe --version
        shell: bash

      - name: Build rfc
        run: |
          cmake -B build -G Ninja .
          cmake --build build
        shell: bash

      - name: Run tests
        run: |
          ctest --test-dir build/tests -VV
        shell: bash
